server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 3s
  svr_name: xshop-user
data:
  database:
    driver: mysql
    user: sweet
    # passwd: dagerous
    passwd: sweet
    port: 3306
    host: "mysql"
    db_name: xshop
  etcd:
    addr: 
      - "etcd:2379"
  # redis:
  #   addr: 127.0.0.1:6379
  #   read_timeout: 0.2s
  #   write_timeout: 0.2s
